/**
 * Bilibili content scraper — uses Bilibili's web search API directly.
 * yt-dlp is still used for downloading, but its BiliBiliSearch extractor
 * is broken against Bilibili's current anti-scraping, so we call the
 * search API via fetch instead.
 */

import { execFile } from "child_process";
import { promisify } from "util";
import fs from "fs";
import os from "os";
import path from "path";
import type { ScraperResult } from "@/lib/db/types";

const execFileAsync = promisify(execFile);

export interface SearchOptions {
  keyword: string;
  page?: number;
  pageSize?: number;
  minViews?: number;
  minDuration?: number;
  maxDuration?: number;
}

interface BiliSearchVideo {
  bvid?: string;
  aid?: number;
  title?: string;
  description?: string;
  pic?: string;
  duration?: string; // "MM:SS" or "H:MM:SS"
  play?: number;
  like?: number;
  author?: string;
  mid?: number;
  pubdate?: number;
  arcurl?: string;
}

function parseDuration(dur: string): number {
  const parts = dur.split(":").map(Number);
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
  if (parts.length === 2) return parts[0] * 60 + parts[1];
  return 0;
}

function stripHtmlTags(s: string): string {
  return s.replace(/<[^>]*>/g, "");
}

/**
 * Write cookie string to Netscape cookies.txt for yt-dlp downloads.
 */
export function writeCookiesFile(cookieStr: string): string {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by ContentMatrix",
  ];

  const pairs = cookieStr.split(";").map((s) => s.trim()).filter(Boolean);
  for (const pair of pairs) {
    const eq = pair.indexOf("=");
    if (eq === -1) continue;
    const name = pair.slice(0, eq).trim();
    const value = pair.slice(eq + 1).trim();
    lines.push(`.bilibili.com\tTRUE\t/\tFALSE\t9999999999\t${name}\t${value}`);
  }

  const tmpFile = path.join(os.tmpdir(), "contentmatrix-bilibili-cookies.txt");
  fs.writeFileSync(tmpFile, lines.join("\n") + "\n", "utf-8");
  return tmpFile;
}

export async function searchBilibili(
  opts: SearchOptions
): Promise<ScraperResult[]> {
  const {
    keyword,
    page = 1,
    pageSize = 20,
    minViews = 5000,
    minDuration = 60,
    maxDuration = 1200,
  } = opts;

  const url = new URL("https://api.bilibili.com/x/web-interface/search/type");
  url.searchParams.set("search_type", "video");
  url.searchParams.set("keyword", keyword);
  url.searchParams.set("page", String(page));
  url.searchParams.set("page_size", String(pageSize));
  url.searchParams.set("order", "totalrank");

  const headers: Record<string, string> = {
    "User-Agent":
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    Referer: "https://search.bilibili.com/",
    Origin: "https://search.bilibili.com",
  };

  const cookieStr = process.env.BILIBILI_COOKIE;
  if (cookieStr) {
    headers["Cookie"] = cookieStr;
  }

  const resp = await fetch(url.toString(), { headers });

  if (!resp.ok) {
    throw new Error(`B站搜索 API 返回 ${resp.status}: ${resp.statusText}`);
  }

  const json = (await resp.json()) as {
    code: number;
    message: string;
    data?: { result?: BiliSearchVideo[] };
  };

  if (json.code !== 0) {
    throw new Error(`B站搜索失败 (code ${json.code}): ${json.message}`);
  }

  const results = json.data?.result ?? [];

  // Keywords that must appear in title or description to confirm relevance
  const kwLower = keyword.toLowerCase();
  const kwChars = keyword.split("");

  return results
    .filter((v) => {
      const dur = parseDuration(v.duration ?? "0:00");
      if (dur < minDuration || dur > maxDuration) return false;
      if ((v.play ?? 0) < minViews) return false;

      // Relevance check: title or description must contain the keyword
      // (or a substantial portion of it for compound terms like "pocomo")
      const title = stripHtmlTags(v.title ?? "").toLowerCase();
      const desc = stripHtmlTags(v.description ?? "").toLowerCase();
      const combined = title + " " + desc;

      if (combined.includes(kwLower)) return true;

      // For Chinese keywords, check if at least 2/3 of characters appear
      const matchCount = kwChars.filter((c) => combined.includes(c)).length;
      if (kwChars.length >= 2 && matchCount >= Math.ceil(kwChars.length * 0.67)) {
        return true;
      }

      return false;
    })
    .map((v) => ({
      platform: "BILIBILI",
      sourceId: v.bvid ?? "",
      sourceType: "VIDEO",
      sourceUrl: v.arcurl ?? `https://www.bilibili.com/video/${v.bvid}`,
      title: stripHtmlTags(v.title ?? ""),
      description: stripHtmlTags(v.description ?? ""),
      thumbnail: v.pic?.startsWith("//") ? `https:${v.pic}` : (v.pic ?? ""),
      duration: parseDuration(v.duration ?? "0:00"),
      viewCount: v.play ?? 0,
      likeCount: v.like ?? 0,
      authorName: v.author ?? "",
      authorId: String(v.mid ?? ""),
      publishedAt: v.pubdate
        ? new Date(v.pubdate * 1000).toISOString()
        : new Date().toISOString(),
    }));
}
